meta-qoriq: Override the default openssl dir for qoriq-atf-tools
Issue: LINUXEXEC-37256

qoriq-atf-tools has been updated to 2.10, in version 2.10, it enables
openssl 3. Fiptool set OPENSSL_DIR := /usr in Makefile, this will
include the system headers and causes build errors. Override it to use
the include directory offered by bitbake to fix build errors:

/usr/include/limits.h:124:3: error: #include_next is a GCC extension [-Werror]
  124 | # include_next <limits.h>
/usr/include/openssl/macros.h:147:4: error: #error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
  147 | #  error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Jianpeng Chang <jianpeng.chang.cn@windriver.com>